name: CI/CD Pipeline

on:
  push:
    branches:
      - test-cicd

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Verify Java version
        run: java -version

      - name: Build with Gradle
        run: ./gradlew build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t thunder0902/creww-backend:test .

      - name: Push Docker image
        run: docker push thunder0902/creww-backend:test

      - name: Pull Docker image for local use
        run: docker pull thunder0902/creww-backend:test

      - name: Clean up Docker images
        run: docker rmi thunder0902/creww-backend:test
